Repository alus-it/AirspaceConverter, pull requests merged in 2025-08, with the labels that each got.

#181 #179: Use fixed, not scientific, format for output in Polish
  src/Polish.cpp
Labels: bug

#185 #184: Do not warn about number of digits for DD:MM.MMM coordinates
  src/OpenAir.cpp
Labels: bug, enhancement

#186 Directory reorganization
  .gitignore
  QtGUI/.qmake.stash
  QtGUI/AboutDialog.cpp
  QtGUI/AboutDialog.hpp
  QtGUI/AboutDialog.ui
  QtGUI/AirspaceConverterQt.pro
  QtGUI/LimitsDialog.cpp
  QtGUI/LimitsDialog.hpp
  QtGUI/LimitsDialog.ui
  QtGUI/MainWindow.cpp
  QtGUI/MainWindow.hpp
  QtGUI/MainWindow.ui
  QtGUI/Makefile
  QtGUI/airspaceconverter-gui
  QtGUI/airspaceconverter128.xpm
  QtGUI/main.cpp
  QtGUI/resources.qrc
  README.md
  VisualStudio/AirspaceConverter/AirspaceConverter.vcxproj.user
  Windows/AirsapceConverter Website.url
  Windows/AirspaceConverter source code.url
  Windows/AirspaceConverter.sln
  Windows/AirspaceConverter/AirspaceConverter.vcxproj
  Windows/AirspaceConverter/AirspaceConverter.vcxproj.filters
  Windows/AirspaceConverter/packages.config
  Windows/AirspaceConverterLib/AirspaceConverterLib.vcxproj
  Windows/AirspaceConverterLib/AirspaceConverterLib.vcxproj.filters
  Windows/AirspaceConverterLib/packages.config
  Windows/AirspaceConverterMFC/AirspaceConverterApp.cpp
  Windows/AirspaceConverterMFC/AirspaceConverterApp.hpp
  Windows/AirspaceConverterMFC/AirspaceConverterDlg.cpp
  Windows/AirspaceConverterMFC/AirspaceConverterDlg.hpp
  Windows/AirspaceConverterMFC/AirspaceConverterMFC.rc
  Windows/AirspaceConverterMFC/AirspaceConverterMFC.vcxproj
  Windows/AirspaceConverterMFC/AirspaceConverterMFC.vcxproj.filters
  Windows/AirspaceConverterMFC/LimitsDlg.cpp
  Windows/AirspaceConverterMFC/LimitsDlg.hpp
  Windows/AirspaceConverterMFC/Processor.cpp
  Windows/AirspaceConverterMFC/Processor.hpp
  Windows/AirspaceConverterMFC/packages.config
  Windows/AirspaceConverterMFC/res/AirspaceConverter.ico
  Windows/AirspaceConverterMFC/res/AirspaceConverterMFC.rc2
  Windows/AirspaceConverterMFC/resource.h
  Windows/AirspaceConverterMFC/stdafx.cpp
  Windows/AirspaceConverterMFC/stdafx.h
  Windows/AirspaceConverterMFC/targetver.h
  Windows/AirspaceConverterSetup64/AirspaceConverterSetup64.vdproj
  Windows/License.rtf
  Windows/Logo.jpg
  Windows/generateReadme.sh
  build.sh
  macOS/MakefileGui.darwin-clang++
Labels: enhancement

#188 187: Upgrade Boost libs to v1.89 for Windows
  Windows/AirspaceConverter/AirspaceConverter.vcxproj
  Windows/AirspaceConverterLib/AirspaceConverterLib.vcxproj
  Windows/AirspaceConverterMFC/AirspaceConverterMFC.vcxproj
Labels: enhancement

#194 added creation of: AppDir/usr/share/pixmaps
  makeAppImage.sh
Labels: bug
